accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

drf_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.


class NewModel(models.Model):
    text = models.CharField(max_length=255, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import NewModel


def hello_world(request):

    if request.method == 'POST':
        input_data = request.POST.get('input_data')

        new_model = NewModel()
        new_model.text = input_data
        new_model.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    new_model_list = NewModel.objects.all()
    return render(request, 'accountapp/hello_world.html',
                  context={'new_model_list': new_model_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


has_ownership = [account_ownership_required, login_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div class="my-5" style="max-width: 600px; margin: auto">

    <div class="my-4">
      <h2>Sign Up</h2>
    </div>

    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill px-5">
    </form>

  </div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div>

    <div class="my-5">
        <h2>Delete Account</h2>
    </div>

    <div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}"
        method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill px-5">
        </form>
    </div>

</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}


  <div>
    <!--  Profile 들어가는 부분  -->
    <div class="my-5">

      {% if target_user.profile.thumb %}
      <img style="width: 13rem; height: 13rem; border-radius: 20rem; object-fit: cover;"
           src="{{ target_user.profile.thumb.url }}" alt="">
      {% elif target_user.profile.image %}
      <img style="width: 13rem; height: 13rem; border-radius: 20rem; object-fit: cover;"
           src="{{ target_user.profile.image.url }}" alt="">
      {% endif %}

      <h1>{{ target_user.profile.nickname }}</h1>
      <h4>{{ target_user.profile.message }}</h4>

    </div>

    <!--  만약 페이지가 본인 페이지라면 개인정보 수정 및 프로필 수정 페이지 시각화  -->
    {% if user == target_user %}
    <div class="my-5">
      <div>
        <a href="{% url 'accountapp:update' pk=target_user.pk %}">
          Update Account
        </a>
      </div>
      <div>
        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
          Update Profile
        </a>
      </div>
    </div>
    {% endif %}

    <!--  본인 작성한 게시글 리스트 들어갈 부분 -->
    <div></div>

  </div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

<div class="my-5">
    <form action="/accounts/hello_world/" method="post">
        {% csrf_token %}
        <input type="text" name="input_data">
        <input type="submit">

    </form>

    <h1>{{ new_model.text }}</h1>
    <p>{{ new_model.created_at }}</p>

    <div>
        {% for new_model in new_model_list %}
            <h5>{{ new_model.text }}</h5>
            <p>{{ new_model.created_at }}</p>
        {% endfor %}
    </div>

</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

    <div class="my-5" style="max-width: 600px; margin: auto;">

        <div class="my-5">
            <h2>Login</h2>
        </div>

        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill px-5">

        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div class="my-5" style="max-width: 600px; margin: auto;">

    <div class="my-5">
      <h3>Update Account</h3>

    </div>

    <div>
      <form action="{% url 'accountapp:update' pk=target_user.pk %}" metho="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-dark rounded-pill px-5">
      </form>
    </div>

  </div>


{% endblock %}