articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

    path('list/', ArticleListView.as_view(), name='list'),
]

drf_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
import sys

from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models

# Create your models here.
from image_processing import thumbnail


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)

    title = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='article/', null=False)
    thumb = models.ImageField(upload_to='article/thumbnail/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.generate_thumbnail()
        super().save(*args, **kwargs)

    def generate_thumbnail(self):
        if self.image:
            output = thumbnail.generate_thumbnail(self.image)
            self.thumb = InMemoryUploadedFile(output, 'ImageField', self.image.name,
                                              'image/jpeg', sys.getsizeof(output), None)

articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, TemplateView, ListView

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


@method_decorator(login_required, 'dispatch')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 2

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div class="my-5" style="max-width: 600px; margin: auto">

    <div class="my-4">
      <h2>Create Article</h2>
    </div>

    <form action="{% url 'articleapp:create' %}"
          enctype="multipart/form-data"
          method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill px-5">
    </form>

  </div>


{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div class="my-5" style="max-width: 600px; margin: auto;">

    <div class="my-5">
      <h3>Delete Article</h3>

    </div>

    <div>
      <form action="{% url 'articleapp:delete' pk=target_article.pk %}" metho="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill px-5">
      </form>
    </div>

  </div>


{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}


  <div style="max-width: 400px; margin: auto;">
    <!--  Profile 들어가는 부분  -->
    <div class="my-5">

      <h1>{{ target_article.title }}</h1>
      <h4>{{ target_article.create_at }}</h4>

      {% if target_article.image %}
      <img style="border-radius: 2rem; width: 100%"
           src="{{ target_article.image.url }}" alt="">
      {% endif %}

    </div>

    <div>

      {{ target_article.content | safe }}

    </div>

    <div>
      {% if target_article.writer == user %}
      <div>
        <a href="{% url 'articleapp:update' pk=target_article.pk %}">Update Article</a>
      </div>
      <div>
        <a href="{% url 'articleapp:delete' pk=target_article.pk %}">Delete Article</a>
      </div>
      {% endif %}
    </div>

  </div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container div {
          width: 180px;
          background-color: antiquewhite;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 8px;
        }

    </style>

    <div class="container" style="max-width: 900px; margin: auto; padding: 0;">
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img style="width: 100%; border-radius: 1rem;"
                         src="{{ article.image.url }}"
                         alt="">
                </a>
            </div>
        {% endfor %}
    </div>

    <div>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="btn btn rounded-pill">
            {{ page_obj.previous_page_number }}
        </a>
        {% endif %}
        <a href="#"
           class="btn btn-dark rounded-pill">
            {{ page_obj.number }}
        </a>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="btn btn rounded-pill">
            {{ page_obj.next_page_number }}
        </a>
        {% endif %}
    </div>

    <script src="{% static 'articleapp/js/magic_grid.js' %}"></script>
    <script>
        let magicGrid = new MagicGrid({
        container: '.container',
        animate: true,
        gutter: 20,
        static: true,
        useMin: true
        });

        magicGrid.listen();

    </script>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div class="my-5" style="max-width: 600px; margin: auto;">

    <div class="my-5">
      <h3>Update Article</h3>

    </div>

    <div>
      <form action="{% url 'articleapp:update' pk=target_article.pk %}" metho="post"
            enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-dark rounded-pill px-5">
      </form>
    </div>

  </div>


{% endblock %}